/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// CollectionsLcdsSummonerRuneInventory
    /// </summary>
    [DataContract]
    public partial class CollectionsLcdsSummonerRuneInventory :  IEquatable<CollectionsLcdsSummonerRuneInventory>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsLcdsSummonerRuneInventory" /> class.
        /// </summary>
        /// <param name="DateString">DateString.</param>
        /// <param name="SummonerId">SummonerId.</param>
        /// <param name="SummonerRunes">SummonerRunes.</param>
        public CollectionsLcdsSummonerRuneInventory(string DateString = default(string), long? SummonerId = default(long?), List<CollectionsLcdsSummonerRune> SummonerRunes = default(List<CollectionsLcdsSummonerRune>))
        {
            this.DateString = DateString;
            this.SummonerId = SummonerId;
            this.SummonerRunes = SummonerRunes;
        }
        
        /// <summary>
        /// Gets or Sets DateString
        /// </summary>
        [DataMember(Name="dateString", EmitDefaultValue=false)]
        public string DateString { get; set; }

        /// <summary>
        /// Gets or Sets SummonerId
        /// </summary>
        [DataMember(Name="summonerId", EmitDefaultValue=false)]
        public long? SummonerId { get; set; }

        /// <summary>
        /// Gets or Sets SummonerRunes
        /// </summary>
        [DataMember(Name="summonerRunes", EmitDefaultValue=false)]
        public List<CollectionsLcdsSummonerRune> SummonerRunes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CollectionsLcdsSummonerRuneInventory {\n");
            sb.Append("  DateString: ").Append(DateString).Append("\n");
            sb.Append("  SummonerId: ").Append(SummonerId).Append("\n");
            sb.Append("  SummonerRunes: ").Append(SummonerRunes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CollectionsLcdsSummonerRuneInventory);
        }

        /// <summary>
        /// Returns true if CollectionsLcdsSummonerRuneInventory instances are equal
        /// </summary>
        /// <param name="other">Instance of CollectionsLcdsSummonerRuneInventory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CollectionsLcdsSummonerRuneInventory other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DateString == other.DateString ||
                    this.DateString != null &&
                    this.DateString.Equals(other.DateString)
                ) && 
                (
                    this.SummonerId == other.SummonerId ||
                    this.SummonerId != null &&
                    this.SummonerId.Equals(other.SummonerId)
                ) && 
                (
                    this.SummonerRunes == other.SummonerRunes ||
                    this.SummonerRunes != null &&
                    this.SummonerRunes.SequenceEqual(other.SummonerRunes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DateString != null)
                    hash = hash * 59 + this.DateString.GetHashCode();
                if (this.SummonerId != null)
                    hash = hash * 59 + this.SummonerId.GetHashCode();
                if (this.SummonerRunes != null)
                    hash = hash * 59 + this.SummonerRunes.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
