/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// CollectionsLcdsSpellBookPageDTO
    /// </summary>
    [DataContract]
    public partial class CollectionsLcdsSpellBookPageDTO :  IEquatable<CollectionsLcdsSpellBookPageDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionsLcdsSpellBookPageDTO" /> class.
        /// </summary>
        /// <param name="CreateDate">CreateDate.</param>
        /// <param name="Current">Current.</param>
        /// <param name="Name">Name.</param>
        /// <param name="PageId">PageId.</param>
        /// <param name="SlotEntries">SlotEntries.</param>
        /// <param name="SummonerId">SummonerId.</param>
        public CollectionsLcdsSpellBookPageDTO(long? CreateDate = default(long?), bool? Current = default(bool?), string Name = default(string), int? PageId = default(int?), List<CollectionsLcdsSlotEntry> SlotEntries = default(List<CollectionsLcdsSlotEntry>), long? SummonerId = default(long?))
        {
            this.CreateDate = CreateDate;
            this.Current = Current;
            this.Name = Name;
            this.PageId = PageId;
            this.SlotEntries = SlotEntries;
            this.SummonerId = SummonerId;
        }
        
        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [DataMember(Name="createDate", EmitDefaultValue=false)]
        public long? CreateDate { get; set; }

        /// <summary>
        /// Gets or Sets Current
        /// </summary>
        [DataMember(Name="current", EmitDefaultValue=false)]
        public bool? Current { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PageId
        /// </summary>
        [DataMember(Name="pageId", EmitDefaultValue=false)]
        public int? PageId { get; set; }

        /// <summary>
        /// Gets or Sets SlotEntries
        /// </summary>
        [DataMember(Name="slotEntries", EmitDefaultValue=false)]
        public List<CollectionsLcdsSlotEntry> SlotEntries { get; set; }

        /// <summary>
        /// Gets or Sets SummonerId
        /// </summary>
        [DataMember(Name="summonerId", EmitDefaultValue=false)]
        public long? SummonerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CollectionsLcdsSpellBookPageDTO {\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PageId: ").Append(PageId).Append("\n");
            sb.Append("  SlotEntries: ").Append(SlotEntries).Append("\n");
            sb.Append("  SummonerId: ").Append(SummonerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CollectionsLcdsSpellBookPageDTO);
        }

        /// <summary>
        /// Returns true if CollectionsLcdsSpellBookPageDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of CollectionsLcdsSpellBookPageDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CollectionsLcdsSpellBookPageDTO other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CreateDate == other.CreateDate ||
                    this.CreateDate != null &&
                    this.CreateDate.Equals(other.CreateDate)
                ) && 
                (
                    this.Current == other.Current ||
                    this.Current != null &&
                    this.Current.Equals(other.Current)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.PageId == other.PageId ||
                    this.PageId != null &&
                    this.PageId.Equals(other.PageId)
                ) && 
                (
                    this.SlotEntries == other.SlotEntries ||
                    this.SlotEntries != null &&
                    this.SlotEntries.SequenceEqual(other.SlotEntries)
                ) && 
                (
                    this.SummonerId == other.SummonerId ||
                    this.SummonerId != null &&
                    this.SummonerId.Equals(other.SummonerId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CreateDate != null)
                    hash = hash * 59 + this.CreateDate.GetHashCode();
                if (this.Current != null)
                    hash = hash * 59 + this.Current.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.PageId != null)
                    hash = hash * 59 + this.PageId.GetHashCode();
                if (this.SlotEntries != null)
                    hash = hash * 59 + this.SlotEntries.GetHashCode();
                if (this.SummonerId != null)
                    hash = hash * 59 + this.SummonerId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
