/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// LCDSLoyaltyRewards
    /// </summary>
    [DataContract]
    public partial class LCDSLoyaltyRewards :  IEquatable<LCDSLoyaltyRewards>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LCDSLoyaltyRewards" /> class.
        /// </summary>
        /// <param name="Champions">Champions.</param>
        /// <param name="IpBoost">IpBoost.</param>
        /// <param name="XpBoost">XpBoost.</param>
        public LCDSLoyaltyRewards(List<LCDSChampionReward> Champions = default(List<LCDSChampionReward>), int? IpBoost = default(int?), int? XpBoost = default(int?))
        {
            this.Champions = Champions;
            this.IpBoost = IpBoost;
            this.XpBoost = XpBoost;
        }
        
        /// <summary>
        /// Gets or Sets Champions
        /// </summary>
        [DataMember(Name="champions", EmitDefaultValue=false)]
        public List<LCDSChampionReward> Champions { get; set; }

        /// <summary>
        /// Gets or Sets IpBoost
        /// </summary>
        [DataMember(Name="ipBoost", EmitDefaultValue=false)]
        public int? IpBoost { get; set; }

        /// <summary>
        /// Gets or Sets XpBoost
        /// </summary>
        [DataMember(Name="xpBoost", EmitDefaultValue=false)]
        public int? XpBoost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LCDSLoyaltyRewards {\n");
            sb.Append("  Champions: ").Append(Champions).Append("\n");
            sb.Append("  IpBoost: ").Append(IpBoost).Append("\n");
            sb.Append("  XpBoost: ").Append(XpBoost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LCDSLoyaltyRewards);
        }

        /// <summary>
        /// Returns true if LCDSLoyaltyRewards instances are equal
        /// </summary>
        /// <param name="other">Instance of LCDSLoyaltyRewards to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LCDSLoyaltyRewards other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Champions == other.Champions ||
                    this.Champions != null &&
                    this.Champions.SequenceEqual(other.Champions)
                ) && 
                (
                    this.IpBoost == other.IpBoost ||
                    this.IpBoost != null &&
                    this.IpBoost.Equals(other.IpBoost)
                ) && 
                (
                    this.XpBoost == other.XpBoost ||
                    this.XpBoost != null &&
                    this.XpBoost.Equals(other.XpBoost)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Champions != null)
                    hash = hash * 59 + this.Champions.GetHashCode();
                if (this.IpBoost != null)
                    hash = hash * 59 + this.IpBoost.GetHashCode();
                if (this.XpBoost != null)
                    hash = hash * 59 + this.XpBoost.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
