/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// LolChatChatLoginDataPacket
    /// </summary>
    [DataContract]
    public partial class LolChatChatLoginDataPacket :  IEquatable<LolChatChatLoginDataPacket>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LolChatChatLoginDataPacket" /> class.
        /// </summary>
        /// <param name="AllSummonerData">AllSummonerData.</param>
        /// <param name="PlayerStatSummaries">PlayerStatSummaries.</param>
        public LolChatChatLoginDataPacket(LolChatChatLoginSummonerData AllSummonerData = default(LolChatChatLoginSummonerData), LolChatChatPlayerStatSummaries PlayerStatSummaries = default(LolChatChatPlayerStatSummaries))
        {
            this.AllSummonerData = AllSummonerData;
            this.PlayerStatSummaries = PlayerStatSummaries;
        }
        
        /// <summary>
        /// Gets or Sets AllSummonerData
        /// </summary>
        [DataMember(Name="allSummonerData", EmitDefaultValue=false)]
        public LolChatChatLoginSummonerData AllSummonerData { get; set; }

        /// <summary>
        /// Gets or Sets PlayerStatSummaries
        /// </summary>
        [DataMember(Name="playerStatSummaries", EmitDefaultValue=false)]
        public LolChatChatPlayerStatSummaries PlayerStatSummaries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LolChatChatLoginDataPacket {\n");
            sb.Append("  AllSummonerData: ").Append(AllSummonerData).Append("\n");
            sb.Append("  PlayerStatSummaries: ").Append(PlayerStatSummaries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LolChatChatLoginDataPacket);
        }

        /// <summary>
        /// Returns true if LolChatChatLoginDataPacket instances are equal
        /// </summary>
        /// <param name="other">Instance of LolChatChatLoginDataPacket to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LolChatChatLoginDataPacket other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AllSummonerData == other.AllSummonerData ||
                    this.AllSummonerData != null &&
                    this.AllSummonerData.Equals(other.AllSummonerData)
                ) && 
                (
                    this.PlayerStatSummaries == other.PlayerStatSummaries ||
                    this.PlayerStatSummaries != null &&
                    this.PlayerStatSummaries.Equals(other.PlayerStatSummaries)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AllSummonerData != null)
                    hash = hash * 59 + this.AllSummonerData.GetHashCode();
                if (this.PlayerStatSummaries != null)
                    hash = hash * 59 + this.PlayerStatSummaries.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
