/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// LolClashRosterDetails
    /// </summary>
    [DataContract]
    public partial class LolClashRosterDetails :  IEquatable<LolClashRosterDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LolClashRosterDetails" /> class.
        /// </summary>
        /// <param name="IconColorId">IconColorId.</param>
        /// <param name="IconId">IconId.</param>
        /// <param name="Name">Name.</param>
        /// <param name="ShortName">ShortName.</param>
        public LolClashRosterDetails(int? IconColorId = default(int?), int? IconId = default(int?), string Name = default(string), string ShortName = default(string))
        {
            this.IconColorId = IconColorId;
            this.IconId = IconId;
            this.Name = Name;
            this.ShortName = ShortName;
        }
        
        /// <summary>
        /// Gets or Sets IconColorId
        /// </summary>
        [DataMember(Name="iconColorId", EmitDefaultValue=false)]
        public int? IconColorId { get; set; }

        /// <summary>
        /// Gets or Sets IconId
        /// </summary>
        [DataMember(Name="iconId", EmitDefaultValue=false)]
        public int? IconId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ShortName
        /// </summary>
        [DataMember(Name="shortName", EmitDefaultValue=false)]
        public string ShortName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LolClashRosterDetails {\n");
            sb.Append("  IconColorId: ").Append(IconColorId).Append("\n");
            sb.Append("  IconId: ").Append(IconId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ShortName: ").Append(ShortName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LolClashRosterDetails);
        }

        /// <summary>
        /// Returns true if LolClashRosterDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of LolClashRosterDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LolClashRosterDetails other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IconColorId == other.IconColorId ||
                    this.IconColorId != null &&
                    this.IconColorId.Equals(other.IconColorId)
                ) && 
                (
                    this.IconId == other.IconId ||
                    this.IconId != null &&
                    this.IconId.Equals(other.IconId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.ShortName == other.ShortName ||
                    this.ShortName != null &&
                    this.ShortName.Equals(other.ShortName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IconColorId != null)
                    hash = hash * 59 + this.IconColorId.GetHashCode();
                if (this.IconId != null)
                    hash = hash * 59 + this.IconId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.ShortName != null)
                    hash = hash * 59 + this.ShortName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
