/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// LolChampionsCollectionsChampionChroma
    /// </summary>
    [DataContract]
    public partial class LolChampionsCollectionsChampionChroma :  IEquatable<LolChampionsCollectionsChampionChroma>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LolChampionsCollectionsChampionChroma" /> class.
        /// </summary>
        /// <param name="ChampionId">ChampionId.</param>
        /// <param name="ChromaPath">ChromaPath.</param>
        /// <param name="Colors">Colors.</param>
        /// <param name="Disabled">Disabled.</param>
        /// <param name="Id">Id.</param>
        /// <param name="LastSelected">LastSelected.</param>
        /// <param name="Name">Name.</param>
        /// <param name="Ownership">Ownership.</param>
        /// <param name="StillObtainable">StillObtainable.</param>
        public LolChampionsCollectionsChampionChroma(int? ChampionId = default(int?), string ChromaPath = default(string), List<string> Colors = default(List<string>), bool? Disabled = default(bool?), int? Id = default(int?), bool? LastSelected = default(bool?), string Name = default(string), LolChampionsCollectionsOwnership Ownership = default(LolChampionsCollectionsOwnership), bool? StillObtainable = default(bool?))
        {
            this.ChampionId = ChampionId;
            this.ChromaPath = ChromaPath;
            this.Colors = Colors;
            this.Disabled = Disabled;
            this.Id = Id;
            this.LastSelected = LastSelected;
            this.Name = Name;
            this.Ownership = Ownership;
            this.StillObtainable = StillObtainable;
        }
        
        /// <summary>
        /// Gets or Sets ChampionId
        /// </summary>
        [DataMember(Name="championId", EmitDefaultValue=false)]
        public int? ChampionId { get; set; }

        /// <summary>
        /// Gets or Sets ChromaPath
        /// </summary>
        [DataMember(Name="chromaPath", EmitDefaultValue=false)]
        public string ChromaPath { get; set; }

        /// <summary>
        /// Gets or Sets Colors
        /// </summary>
        [DataMember(Name="colors", EmitDefaultValue=false)]
        public List<string> Colors { get; set; }

        /// <summary>
        /// Gets or Sets Disabled
        /// </summary>
        [DataMember(Name="disabled", EmitDefaultValue=false)]
        public bool? Disabled { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets LastSelected
        /// </summary>
        [DataMember(Name="lastSelected", EmitDefaultValue=false)]
        public bool? LastSelected { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Ownership
        /// </summary>
        [DataMember(Name="ownership", EmitDefaultValue=false)]
        public LolChampionsCollectionsOwnership Ownership { get; set; }

        /// <summary>
        /// Gets or Sets StillObtainable
        /// </summary>
        [DataMember(Name="stillObtainable", EmitDefaultValue=false)]
        public bool? StillObtainable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LolChampionsCollectionsChampionChroma {\n");
            sb.Append("  ChampionId: ").Append(ChampionId).Append("\n");
            sb.Append("  ChromaPath: ").Append(ChromaPath).Append("\n");
            sb.Append("  Colors: ").Append(Colors).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LastSelected: ").Append(LastSelected).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Ownership: ").Append(Ownership).Append("\n");
            sb.Append("  StillObtainable: ").Append(StillObtainable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LolChampionsCollectionsChampionChroma);
        }

        /// <summary>
        /// Returns true if LolChampionsCollectionsChampionChroma instances are equal
        /// </summary>
        /// <param name="other">Instance of LolChampionsCollectionsChampionChroma to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LolChampionsCollectionsChampionChroma other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ChampionId == other.ChampionId ||
                    this.ChampionId != null &&
                    this.ChampionId.Equals(other.ChampionId)
                ) && 
                (
                    this.ChromaPath == other.ChromaPath ||
                    this.ChromaPath != null &&
                    this.ChromaPath.Equals(other.ChromaPath)
                ) && 
                (
                    this.Colors == other.Colors ||
                    this.Colors != null &&
                    this.Colors.SequenceEqual(other.Colors)
                ) && 
                (
                    this.Disabled == other.Disabled ||
                    this.Disabled != null &&
                    this.Disabled.Equals(other.Disabled)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.LastSelected == other.LastSelected ||
                    this.LastSelected != null &&
                    this.LastSelected.Equals(other.LastSelected)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.Ownership == other.Ownership ||
                    this.Ownership != null &&
                    this.Ownership.Equals(other.Ownership)
                ) && 
                (
                    this.StillObtainable == other.StillObtainable ||
                    this.StillObtainable != null &&
                    this.StillObtainable.Equals(other.StillObtainable)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ChampionId != null)
                    hash = hash * 59 + this.ChampionId.GetHashCode();
                if (this.ChromaPath != null)
                    hash = hash * 59 + this.ChromaPath.GetHashCode();
                if (this.Colors != null)
                    hash = hash * 59 + this.Colors.GetHashCode();
                if (this.Disabled != null)
                    hash = hash * 59 + this.Disabled.GetHashCode();
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.LastSelected != null)
                    hash = hash * 59 + this.LastSelected.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.Ownership != null)
                    hash = hash * 59 + this.Ownership.GetHashCode();
                if (this.StillObtainable != null)
                    hash = hash * 59 + this.StillObtainable.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
