/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// Defines LolLobbyTeamBuilderMatchmakingDodgeState
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LolLobbyTeamBuilderMatchmakingDodgeState
    {
        
        /// <summary>
        /// Enum Invalid for "Invalid"
        /// </summary>
        [EnumMember(Value = "Invalid")]
        Invalid,
        
        /// <summary>
        /// Enum PartyDodged for "PartyDodged"
        /// </summary>
        [EnumMember(Value = "PartyDodged")]
        PartyDodged,
        
        /// <summary>
        /// Enum StrangerDodged for "StrangerDodged"
        /// </summary>
        [EnumMember(Value = "StrangerDodged")]
        StrangerDodged,
        
        /// <summary>
        /// Enum TournamentDodged for "TournamentDodged"
        /// </summary>
        [EnumMember(Value = "TournamentDodged")]
        TournamentDodged
    }

}
