/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// LolLootRecipeMetadata
    /// </summary>
    [DataContract]
    public partial class LolLootRecipeMetadata :  IEquatable<LolLootRecipeMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LolLootRecipeMetadata" /> class.
        /// </summary>
        /// <param name="BonusDescriptions">BonusDescriptions.</param>
        /// <param name="GuaranteedDescriptions">GuaranteedDescriptions.</param>
        /// <param name="TooltipsDisabled">TooltipsDisabled.</param>
        public LolLootRecipeMetadata(List<LolLootLootDescription> BonusDescriptions = default(List<LolLootLootDescription>), List<LolLootLootDescription> GuaranteedDescriptions = default(List<LolLootLootDescription>), bool? TooltipsDisabled = default(bool?))
        {
            this.BonusDescriptions = BonusDescriptions;
            this.GuaranteedDescriptions = GuaranteedDescriptions;
            this.TooltipsDisabled = TooltipsDisabled;
        }
        
        /// <summary>
        /// Gets or Sets BonusDescriptions
        /// </summary>
        [DataMember(Name="bonusDescriptions", EmitDefaultValue=false)]
        public List<LolLootLootDescription> BonusDescriptions { get; set; }

        /// <summary>
        /// Gets or Sets GuaranteedDescriptions
        /// </summary>
        [DataMember(Name="guaranteedDescriptions", EmitDefaultValue=false)]
        public List<LolLootLootDescription> GuaranteedDescriptions { get; set; }

        /// <summary>
        /// Gets or Sets TooltipsDisabled
        /// </summary>
        [DataMember(Name="tooltipsDisabled", EmitDefaultValue=false)]
        public bool? TooltipsDisabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LolLootRecipeMetadata {\n");
            sb.Append("  BonusDescriptions: ").Append(BonusDescriptions).Append("\n");
            sb.Append("  GuaranteedDescriptions: ").Append(GuaranteedDescriptions).Append("\n");
            sb.Append("  TooltipsDisabled: ").Append(TooltipsDisabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LolLootRecipeMetadata);
        }

        /// <summary>
        /// Returns true if LolLootRecipeMetadata instances are equal
        /// </summary>
        /// <param name="other">Instance of LolLootRecipeMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LolLootRecipeMetadata other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BonusDescriptions == other.BonusDescriptions ||
                    this.BonusDescriptions != null &&
                    this.BonusDescriptions.SequenceEqual(other.BonusDescriptions)
                ) && 
                (
                    this.GuaranteedDescriptions == other.GuaranteedDescriptions ||
                    this.GuaranteedDescriptions != null &&
                    this.GuaranteedDescriptions.SequenceEqual(other.GuaranteedDescriptions)
                ) && 
                (
                    this.TooltipsDisabled == other.TooltipsDisabled ||
                    this.TooltipsDisabled != null &&
                    this.TooltipsDisabled.Equals(other.TooltipsDisabled)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BonusDescriptions != null)
                    hash = hash * 59 + this.BonusDescriptions.GetHashCode();
                if (this.GuaranteedDescriptions != null)
                    hash = hash * 59 + this.GuaranteedDescriptions.GetHashCode();
                if (this.TooltipsDisabled != null)
                    hash = hash * 59 + this.TooltipsDisabled.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
