/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// MatchmakingLcdsMatchMakerPayload
    /// </summary>
    [DataContract]
    public partial class MatchmakingLcdsMatchMakerPayload :  IEquatable<MatchmakingLcdsMatchMakerPayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchmakingLcdsMatchMakerPayload" /> class.
        /// </summary>
        /// <param name="LEAVER_BUSTER_ACCESS_TOKEN">LEAVER_BUSTER_ACCESS_TOKEN.</param>
        public MatchmakingLcdsMatchMakerPayload(string LEAVER_BUSTER_ACCESS_TOKEN = default(string))
        {
            this.LEAVER_BUSTER_ACCESS_TOKEN = LEAVER_BUSTER_ACCESS_TOKEN;
        }
        
        /// <summary>
        /// Gets or Sets LEAVER_BUSTER_ACCESS_TOKEN
        /// </summary>
        [DataMember(Name="LEAVER_BUSTER_ACCESS_TOKEN", EmitDefaultValue=false)]
        public string LEAVER_BUSTER_ACCESS_TOKEN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatchmakingLcdsMatchMakerPayload {\n");
            sb.Append("  LEAVER_BUSTER_ACCESS_TOKEN: ").Append(LEAVER_BUSTER_ACCESS_TOKEN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MatchmakingLcdsMatchMakerPayload);
        }

        /// <summary>
        /// Returns true if MatchmakingLcdsMatchMakerPayload instances are equal
        /// </summary>
        /// <param name="other">Instance of MatchmakingLcdsMatchMakerPayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatchmakingLcdsMatchMakerPayload other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.LEAVER_BUSTER_ACCESS_TOKEN == other.LEAVER_BUSTER_ACCESS_TOKEN ||
                    this.LEAVER_BUSTER_ACCESS_TOKEN != null &&
                    this.LEAVER_BUSTER_ACCESS_TOKEN.Equals(other.LEAVER_BUSTER_ACCESS_TOKEN)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.LEAVER_BUSTER_ACCESS_TOKEN != null)
                    hash = hash * 59 + this.LEAVER_BUSTER_ACCESS_TOKEN.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
