/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// Serialization format for remoting requests and results.
    /// </summary>
    /// <value>Serialization format for remoting requests and results.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RemotingSerializedFormat
    {
        
        /// <summary>
        /// Enum JSON for "JSON"
        /// </summary>
        [EnumMember(Value = "JSON")]
        JSON,
        
        /// <summary>
        /// Enum YAML for "YAML"
        /// </summary>
        [EnumMember(Value = "YAML")]
        YAML,
        
        /// <summary>
        /// Enum MsgPack for "MsgPack"
        /// </summary>
        [EnumMember(Value = "MsgPack")]
        MsgPack
    }

}
