/* 
 * LeagueClient
 *
 * 7.23.209.3517
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LeagueClientApi.Model
{
    /// <summary>
    /// RewardDetails
    /// </summary>
    [DataContract]
    public partial class RewardDetails :  IEquatable<RewardDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RewardDetails" /> class.
        /// </summary>
        /// <param name="RosterId">RosterId.</param>
        /// <param name="TeamMemberIds">TeamMemberIds.</param>
        /// <param name="TournamentId">TournamentId.</param>
        public RewardDetails(long? RosterId = default(long?), List<long?> TeamMemberIds = default(List<long?>), long? TournamentId = default(long?))
        {
            this.RosterId = RosterId;
            this.TeamMemberIds = TeamMemberIds;
            this.TournamentId = TournamentId;
        }
        
        /// <summary>
        /// Gets or Sets RosterId
        /// </summary>
        [DataMember(Name="rosterId", EmitDefaultValue=false)]
        public long? RosterId { get; set; }

        /// <summary>
        /// Gets or Sets TeamMemberIds
        /// </summary>
        [DataMember(Name="teamMemberIds", EmitDefaultValue=false)]
        public List<long?> TeamMemberIds { get; set; }

        /// <summary>
        /// Gets or Sets TournamentId
        /// </summary>
        [DataMember(Name="tournamentId", EmitDefaultValue=false)]
        public long? TournamentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RewardDetails {\n");
            sb.Append("  RosterId: ").Append(RosterId).Append("\n");
            sb.Append("  TeamMemberIds: ").Append(TeamMemberIds).Append("\n");
            sb.Append("  TournamentId: ").Append(TournamentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as RewardDetails);
        }

        /// <summary>
        /// Returns true if RewardDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of RewardDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RewardDetails other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RosterId == other.RosterId ||
                    this.RosterId != null &&
                    this.RosterId.Equals(other.RosterId)
                ) && 
                (
                    this.TeamMemberIds == other.TeamMemberIds ||
                    this.TeamMemberIds != null &&
                    this.TeamMemberIds.SequenceEqual(other.TeamMemberIds)
                ) && 
                (
                    this.TournamentId == other.TournamentId ||
                    this.TournamentId != null &&
                    this.TournamentId.Equals(other.TournamentId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RosterId != null)
                    hash = hash * 59 + this.RosterId.GetHashCode();
                if (this.TeamMemberIds != null)
                    hash = hash * 59 + this.TeamMemberIds.GetHashCode();
                if (this.TournamentId != null)
                    hash = hash * 59 + this.TournamentId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
